// <auto-generated />
using System;
using CallCenter.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CallCenter.Persistence.Migrations
{
    [DbContext(typeof(CallCenterDbContext))]
    [Migration("20260915174858_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CallCenter.Domain.Entities.Agent", b =>
                {
                    b.Property<Guid>("AgentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CurrentState")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("StateChangedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AgentId");

                    b.HasIndex("Extension")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("CallCenter.Domain.Entities.AgentQueue", b =>
                {
                    b.Property<Guid>("AgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QueueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SkillLevel")
                        .HasColumnType("int");

                    b.HasKey("AgentId", "QueueId");

                    b.HasIndex("QueueId");

                    b.ToTable("AgentQueues");
                });

            modelBuilder.Entity("CallCenter.Domain.Entities.AgentStateLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("EndTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("SubReason")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.ToTable("AgentStateLogs");
                });

            modelBuilder.Entity("CallCenter.Domain.Entities.Call", b =>
                {
                    b.Property<Guid>("CallId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AgentNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset?>("AnsweredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CRMContactId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CallUuid")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CallerNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DestinationNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<Guid?>("DispositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("HoldDurationSeconds")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("InitiatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("QueueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TalkDurationSeconds")
                        .HasColumnType("int");

                    b.Property<int>("TotalDurationSeconds")
                        .HasColumnType("int");

                    b.Property<int>("WaitDurationSeconds")
                        .HasColumnType("int");

                    b.HasKey("CallId");

                    b.HasIndex("AgentId");

                    b.HasIndex("CallUuid")
                        .IsUnique();

                    b.HasIndex("CallerNumber");

                    b.HasIndex("DispositionId");

                    b.HasIndex("QueueId");

                    b.HasIndex("InitiatedAt", "Status");

                    b.ToTable("Calls");
                });

            modelBuilder.Entity("CallCenter.Domain.Entities.CallRecording", b =>
                {
                    b.Property<Guid>("RecordingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AudioChannels")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("CallId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<string>("FileHashSHA256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("OffloadedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("StorageBucket")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("RecordingId");

                    b.HasIndex("CallId")
                        .IsUnique();

                    b.ToTable("CallRecordings");
                });

            modelBuilder.Entity("CallCenter.Domain.Entities.CallSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CallId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChannelUuid")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset?>("EndTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("HangupCause")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LegType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("SessionId");

                    b.HasIndex("CallId");

                    b.ToTable("CallSessions");
                });

            modelBuilder.Entity("CallCenter.Domain.Entities.Campaign", b =>
                {
                    b.Property<Guid>("CampaignId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("EndDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CampaignId");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("CallCenter.Domain.Entities.Disposition", b =>
                {
                    b.Property<Guid>("DispositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiresFollowup")
                        .HasColumnType("bit");

                    b.HasKey("DispositionId");

                    b.ToTable("Dispositions");

                    b.HasData(
                        new
                        {
                            DispositionId = new Guid("d1111111-1111-1111-1111-111111111111"),
                            Category = "Support",
                            Code = "RESOLVED",
                            Description = "Query Resolved on Call",
                            IsActive = true,
                            RequiresFollowup = false
                        },
                        new
                        {
                            DispositionId = new Guid("d2222222-2222-2222-2222-222222222222"),
                            Category = "Support",
                            Code = "ESCALATED",
                            Description = "Issue Escalated to Tier 2",
                            IsActive = true,
                            RequiresFollowup = true
                        },
                        new
                        {
                            DispositionId = new Guid("d3333333-3333-3333-3333-333333333333"),
                            Category = "General",
                            Code = "CALLBACK_REQ",
                            Description = "Customer Requested Callback",
                            IsActive = true,
                            RequiresFollowup = true
                        },
                        new
                        {
                            DispositionId = new Guid("d4444444-4444-4444-4444-444444444444"),
                            Category = "Sales",
                            Code = "INTERESTED",
                            Description = "Prospect Interested in Offer",
                            IsActive = true,
                            RequiresFollowup = false
                        },
                        new
                        {
                            DispositionId = new Guid("d5555555-5555-5555-5555-555555555555"),
                            Category = "Sales",
                            Code = "NOT_INTERESTED",
                            Description = "Prospect Declined Offer",
                            IsActive = true,
                            RequiresFollowup = false
                        });
                });

            modelBuilder.Entity("CallCenter.Domain.Entities.Queue", b =>
                {
                    b.Property<Guid>("QueueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxWaitTimeoutSeconds")
                        .HasColumnType("int");

                    b.Property<string>("QueueName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SLAThresholdSeconds")
                        .HasColumnType("int");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("QueueId");

                    b.ToTable("Queues");
                });

            modelBuilder.Entity("CallCenter.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "System Administrator",
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Call Center Team Lead / Supervisor",
                            RoleName = "Supervisor"
                        },
                        new
                        {
                            RoleId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Description = "Contact Center Agent",
                            RoleName = "Agent"
                        });
                });

            modelBuilder.Entity("CallCenter.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CallCenter.Domain.Entities.Agent", b =>
                {
                    b.HasOne("CallCenter.Domain.Entities.User", "User")
                        .WithOne("AgentProfile")
                        .HasForeignKey("CallCenter.Domain.Entities.Agent", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CallCenter.Domain.Entities.AgentQueue", b =>
                {
                    b.HasOne("CallCenter.Domain.Entities.Agent", "Agent")
                        .WithMany("AgentQueues")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CallCenter.Domain.Entities.Queue", "Queue")
                        .WithMany("AgentQueues")
                        .HasForeignKey("QueueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Queue");
                });

            modelBuilder.Entity("CallCenter.Domain.Entities.AgentStateLog", b =>
                {
                    b.HasOne("CallCenter.Domain.Entities.Agent", "Agent")
                        .WithMany("StateLogs")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("CallCenter.Domain.Entities.Call", b =>
                {
                    b.HasOne("CallCenter.Domain.Entities.Agent", "Agent")
                        .WithMany("HandledCalls")
                        .HasForeignKey("AgentId");

                    b.HasOne("CallCenter.Domain.Entities.Disposition", "Disposition")
                        .WithMany()
                        .HasForeignKey("DispositionId");

                    b.HasOne("CallCenter.Domain.Entities.Queue", "Queue")
                        .WithMany("Calls")
                        .HasForeignKey("QueueId");

                    b.Navigation("Agent");

                    b.Navigation("Disposition");

                    b.Navigation("Queue");
                });

            modelBuilder.Entity("CallCenter.Domain.Entities.CallRecording", b =>
                {
                    b.HasOne("CallCenter.Domain.Entities.Call", "Call")
                        .WithOne("Recording")
                        .HasForeignKey("CallCenter.Domain.Entities.CallRecording", "CallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Call");
                });

            modelBuilder.Entity("CallCenter.Domain.Entities.CallSession", b =>
                {
                    b.HasOne("CallCenter.Domain.Entities.Call", "Call")
                        .WithMany("Sessions")
                        .HasForeignKey("CallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Call");
                });

            modelBuilder.Entity("CallCenter.Domain.Entities.User", b =>
                {
                    b.HasOne("CallCenter.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CallCenter.Domain.Entities.Agent", b =>
                {
                    b.Navigation("AgentQueues");

                    b.Navigation("HandledCalls");

                    b.Navigation("StateLogs");
                });

            modelBuilder.Entity("CallCenter.Domain.Entities.Call", b =>
                {
                    b.Navigation("Recording");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("CallCenter.Domain.Entities.Queue", b =>
                {
                    b.Navigation("AgentQueues");

                    b.Navigation("Calls");
                });

            modelBuilder.Entity("CallCenter.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CallCenter.Domain.Entities.User", b =>
                {
                    b.Navigation("AgentProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
